name: Build & Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: Build & Test
    runs-on: macos-15
    
    steps:
    - name: Show Swift Version
      run: |
        swift --version
        swift package --version
    - uses: actions/checkout@v4
    - name: Build
      run: |
        swift build -v
    - name: Test
      run: |
        swift test -v
